version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always

  # geoip:
  #   image: maxmindinc/geoipupdate
  #   environment:
  #     - GEOIPUPDATE_EDITION_IDS=GeoLite2-Country
  #     - GEOIPUPDATE_FREQUENCY=168 # update every 7 days
  #   env_file:
  #     - plausible.env
  #   volumes:
  #     - geoip:/usr/share/GeoIP

  plausible_db:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend
    restart: always

  plausible_events_db:
    image: yandex/clickhouse-server:latest
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - backend
    restart: always

  plausible:
    image: plausible/analytics:latest
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - mail
      # - geoip
      - plausible_db
      - plausible_events_db
    env_file:
      - plausible.env
    networks:
      - backend
      - frontend
    # environment:
    #   - GEOLITE2_COUNTRY_DB=/geoip/GeoLite2-Country.mmdb
    # volumes:
    #   - geoip:/geoip:ro
    restart: always
    labels:
      # enable traefik
      traefik.enable: "true"

      traefik.http.routers.plausible.rule: "Host(`plausible.atherantimes.com`)"
      traefik.http.services.plausible.loadbalancer.server.port: "8000"
      traefik.http.routers.plausible.entrypoints: "websecure"
      traefik.http.routers.plausible.tls.certresolver: "myresolver"

volumes:
  db-data:
  event-data:
  # geoip:

networks:
  frontend:
    external: true
    name: frontend
  backend:
    external: true
    name: backend
