version: "3.8"

volumes:
  mariadb-data:
  ghost-data:
  

services:
  # cms
  ghost:
    image: ghost:4-alpine
    # container_name: ghost
    restart: always
    volumes:
      # make ghost stateful
      - ghost-data:/var/lib/ghost/content
    ports:
      - 2368:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      # database__connection__password: example
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: http://localhost:2368
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development
    env_file:
      - config.env
    labels:
      # enables auto updates
      - "com.centurylinklabs.watchtower.enable=true"
      # traefik set host
      - "traefik.http.routers.ghost.rule=Host(`cms.atherantimes.com`)"
      - "traefik.http.services.ghost.loadbalancer.server.port=2368"
      # enables tls
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.tls.certresolver=letsEncrypt
    # set containers required by ghost
    depends_on:
      - db

  # db for cms
  db:
    image: mariadb:10
    # container_name: mariadb
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      # MYSQL_ROOT_PASSWORD: example
    env_file:
      - config.env
    labels:
      # enables auto updates
      - "com.centurylinklabs.watchtower.enable=true"

  # auto updates containers
  watchtower:
    image: containrrr/watchtower
    # container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - /root/.docker/config.json:/config.json
    environment:
      # set containers timezone
      TZ: "America/New_York"
      WATCHTOWER_CLEANUP: "true"
      # requires label to auto update containers
      WATCHTOWER_LABEL_ENABLE: "true"
      # WATCHTOWER_POLL_INTERVAL: 21600
      # update at 3 am
      WATCHTOWER_SCHEDULE: "0 0 3 * * *"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # # simple smtp server
  # mail:
  #   image: bytemark/smtp
  #   restart: always
