version: "3.8"

services:
  # entry point to every app
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.4
    restart: always
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker
      # only allow traefik to proxy specific services
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443

      # https stuff

      # set to http challange
      - --certificatesresolvers.myhttpchallenge.acme.httpchallenge=true
      # make web entry point for challenge
      - --certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web
      # acme server for testing
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      # email
      - --certificatesresolvers.myhttpchallenge.acme.email=acme@atherantimes.com
      # path to config file
      - --certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json
    ports:
      # The HTTP port
      - "80:80"
      # HTTPS
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
