version: "3.8"

services:
  # entry point to every app
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.4
    restart: always
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # https stuff

      # set to http challange
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      # make web entry point for challenge
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      # acme server for testing
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"\
      # email
      - "--certificatesresolvers.myresolver.acme.email=acme@atherantimes.com"
      # path to config file
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      # The HTTP port
      - "80:80"
      # HTTPS
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
