version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce
    # command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    # networks:
    #   - agent_network
    #   - proxy-net
    environment:
      TZ: "America/New_York"
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`example.com`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

volumes:
  portainer_data:
